# DigitalOcean App Platform Configuration
# This deploys the background worker service for long-running tasks

name: epic-ai-platform
region: nyc

# ===========================================
# SERVICES (Web-accessible)
# ===========================================

services:
  # n8n Workflow Automation
  - name: n8n
    image:
      registry_type: DOCKER_HUB
      registry: n8nio
      repository: n8n
      tag: latest
    instance_count: 1
    instance_size_slug: professional-xs  # 1 vCPU, 2GB RAM (~$12/mo)
    http_port: 5678
    routes:
      - path: /
    health_check:
      http_path: /healthz
      initial_delay_seconds: 30
      period_seconds: 10
    envs:
      # Basic Config
      - key: N8N_HOST
        scope: RUN_TIME
        value: ${APP_DOMAIN}
      - key: N8N_PORT
        scope: RUN_TIME
        value: "5678"
      - key: N8N_PROTOCOL
        scope: RUN_TIME
        value: https
      - key: WEBHOOK_URL
        scope: RUN_TIME
        value: https://${APP_DOMAIN}/
      # Database (use same PostgreSQL)
      - key: DB_TYPE
        scope: RUN_TIME
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        scope: RUN_TIME
        value: ${epic-ai-db.HOSTNAME}
      - key: DB_POSTGRESDB_PORT
        scope: RUN_TIME
        value: ${epic-ai-db.PORT}
      - key: DB_POSTGRESDB_DATABASE
        scope: RUN_TIME
        value: n8n
      - key: DB_POSTGRESDB_USER
        scope: RUN_TIME
        value: ${epic-ai-db.USERNAME}
      - key: DB_POSTGRESDB_PASSWORD
        scope: RUN_TIME
        type: SECRET
      # Encryption
      - key: N8N_ENCRYPTION_KEY
        scope: RUN_TIME
        type: SECRET
      # Authentication
      - key: N8N_BASIC_AUTH_ACTIVE
        scope: RUN_TIME
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        scope: RUN_TIME
        type: SECRET
      - key: N8N_BASIC_AUTH_PASSWORD
        scope: RUN_TIME
        type: SECRET
      # Execution Settings
      - key: EXECUTIONS_DATA_PRUNE
        scope: RUN_TIME
        value: "true"
      - key: EXECUTIONS_DATA_MAX_AGE
        scope: RUN_TIME
        value: "168"  # 7 days in hours
      - key: GENERIC_TIMEZONE
        scope: RUN_TIME
        value: America/New_York
      # Queue Mode (for scaling)
      - key: EXECUTIONS_MODE
        scope: RUN_TIME
        value: regular  # Use 'queue' for high volume with Redis
      # External Hooks (connect to Epic AI)
      - key: EPIC_AI_API_URL
        scope: RUN_TIME
        value: ${_self.PUBLIC_URL}
      - key: EPIC_AI_WEBHOOK_SECRET
        scope: RUN_TIME
        type: SECRET

  # Voice Service (Flask backend for LiveKit and Magnus Billing)
  - name: voice-service
    github:
      repo: epicdm/epic-ai
      branch: main
      deploy_on_push: true
    source_dir: apps/voice-service
    dockerfile_path: apps/voice-service/Dockerfile
    instance_count: 1
    instance_size_slug: basic-xs  # 1 vCPU, 512MB RAM
    http_port: 8000
    routes:
      - path: /voice
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 30
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: REDIS_URL
        scope: RUN_TIME
        type: SECRET
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: LIVEKIT_URL
        scope: RUN_TIME
        type: SECRET
      - key: LIVEKIT_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: LIVEKIT_API_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: MAGNUS_BILLING_API_URL
        scope: RUN_TIME
        type: SECRET
      - key: MAGNUS_BILLING_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: MAGNUS_BILLING_ACCOUNT_ID
        scope: RUN_TIME
        type: SECRET
      - key: LOG_LEVEL
        scope: RUN_TIME
        value: INFO

# ===========================================
# WORKERS (Background processing)
# ===========================================

workers:
  # Background worker for content generation, scraping, etc.
  # T050: Health check available on internal port 3001 (/health)
  # NOTE: Builds from monorepo root to resolve @epic-ai/database workspace dependency
  - name: content-worker
    github:
      repo: epicdm/epic-ai
      branch: main
      deploy_on_push: true
    # NO source_dir - build from monorepo root for workspace dependencies
    build_command: |
      corepack enable
      corepack prepare pnpm@9.0.0 --activate
      pnpm install --frozen-lockfile
      cd packages/database && pnpm build && cd ../..
      cd apps/workers && pnpm build
    run_command: node apps/workers/dist/index.js
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: REDIS_URL
        scope: RUN_TIME
        type: SECRET
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: NODE_ENV
        scope: RUN_TIME
        value: production
      - key: N8N_WEBHOOK_URL
        scope: RUN_TIME
        value: https://${n8n.PUBLIC_URL}
      # T050: Health check port (internal only, not exposed externally)
      - key: HEALTH_PORT
        scope: RUN_TIME
        value: "3001"

# ===========================================
# JOBS (Scheduled tasks)
# ===========================================

jobs:
  - name: content-scheduler
    kind: PRE_DEPLOY
    github:
      repo: epicdm/epic-ai
      branch: main
    # NO source_dir - build from monorepo root for workspace dependencies
    build_command: |
      corepack enable
      corepack prepare pnpm@9.0.0 --activate
      pnpm install --frozen-lockfile
      cd packages/database && pnpm build && cd ../..
      cd apps/workers && pnpm build
    run_command: node apps/workers/dist/scheduler.js
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: REDIS_URL
        scope: RUN_TIME
        type: SECRET

# ===========================================
# DATABASES
# ===========================================

databases:
  - name: epic-ai-db
    engine: PG
    version: "16"
    size: db-s-1vcpu-1gb
    num_nodes: 1
