#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Project: Epic AI Repository Analysis and Local Development Setup

set -e

echo "========================================"
echo "Epic AI - Development Environment Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start on port $port${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready on port $port${NC}"
}

# ============================================
# PREREQUISITES CHECK
# ============================================

echo ""
echo -e "${BLUE}Checking prerequisites...${NC}"

# Check pnpm
if ! command -v pnpm &> /dev/null; then
    echo -e "${RED}pnpm is not installed. Please install pnpm first.${NC}"
    echo "  npm install -g pnpm"
    exit 1
fi
echo -e "${GREEN}✓ pnpm found${NC}"

# Check Docker
if ! command -v docker &> /dev/null; then
    echo -e "${YELLOW}Warning: Docker not found. PostgreSQL and Redis must be configured manually.${NC}"
else
    echo -e "${GREEN}✓ Docker found${NC}"
fi

# Check docker-compose
if ! command -v docker-compose &> /dev/null; then
    echo -e "${YELLOW}Warning: docker-compose not found. Using 'docker compose' instead.${NC}"
    DOCKER_COMPOSE="docker compose"
else
    echo -e "${GREEN}✓ docker-compose found${NC}"
    DOCKER_COMPOSE="docker-compose"
fi

# ============================================
# ENVIRONMENT SETUP
# ============================================

echo ""
echo -e "${BLUE}Setting up environment...${NC}"

# Create .env.local if it doesn't exist
if [ ! -f .env.local ]; then
    if [ -f .env.example ]; then
        cp .env.example .env.local
        echo -e "${GREEN}✓ Created .env.local from .env.example${NC}"
        echo -e "${YELLOW}  Note: You need to set CLERK_SECRET_KEY and NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY${NC}"
    else
        echo -e "${RED}Warning: .env.example not found${NC}"
    fi
else
    echo -e "${GREEN}✓ .env.local already exists${NC}"
fi

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo -e "${BLUE}Installing dependencies...${NC}"

pnpm install
echo -e "${GREEN}✓ Dependencies installed${NC}"

# ============================================
# START DOCKER SERVICES
# ============================================

echo ""
echo -e "${BLUE}Starting Docker services...${NC}"

# Start only postgres and redis (not voice-service which is experimental)
$DOCKER_COMPOSE up -d postgres redis

# Wait for services to be healthy
echo "Waiting for PostgreSQL to be healthy..."
sleep 5

# Check PostgreSQL health
if docker exec epic-ai-postgres pg_isready -U epic -d epic_ai > /dev/null 2>&1; then
    echo -e "${GREEN}✓ PostgreSQL ready${NC}"
else
    echo -e "${RED}PostgreSQL health check failed. Waiting longer...${NC}"
    sleep 10
fi

# Check Redis health
if docker exec epic-ai-redis redis-cli ping > /dev/null 2>&1; then
    echo -e "${GREEN}✓ Redis ready${NC}"
else
    echo -e "${RED}Redis health check failed.${NC}"
fi

# ============================================
# DATABASE SETUP
# ============================================

echo ""
echo -e "${BLUE}Setting up database...${NC}"

# Push Prisma schema
pnpm db:push
echo -e "${GREEN}✓ Database schema pushed${NC}"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  PostgreSQL: localhost:5432"
echo "  Redis:      localhost:6379"
echo ""
echo "To start development:"
echo "  pnpm dev           - Start web app (port 3000)"
echo "  pnpm db:studio     - Open Prisma Studio (port 5555)"
echo ""
echo "Individual apps:"
echo "  pnpm --filter @epic-ai/web dev       - Start web only"
echo "  pnpm --filter @epic-ai/workers dev   - Start workers only"
echo ""
echo "Environment variables needed for full functionality:"
echo "  CLERK_SECRET_KEY                     - From Clerk dashboard"
echo "  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY    - From Clerk dashboard"
echo "  OPENAI_API_KEY                       - For AI features (optional)"
echo ""
